version: "1"
# si se esta sin acceso a base de datos, tambien incluir los datos dentro de .env
services:

  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:4.4-focal"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
